# Generated by Django 4.2.6 on 2023-10-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cost', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('cash', 'cash'), ('credit', 'credit')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cost', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('cash', 'cash'), ('credit', 'credit')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('cash', models.IntegerField(default=0)),
                ('credits', models.IntegerField(default=0)),
            ],
        ),
    ]
