# Generated by Django 4.2.6 on 2023-10-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treasury',
            old_name='credits',
            new_name='credit',
        ),
    ]
