# Generated by Django 4.2.6 on 2023-10-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_credits_treasury_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='income',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
