# Generated by Django 4.2.6 on 2023-10-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_expence_cost_alter_income_cost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expence',
            new_name='Expense',
        ),
    ]
